config/routes.rb
Rails.application.routes.draw do
  resources :addresses
  resources :products
  resources :orders
  resources :users
  resources :customers
  # get 'home/index'
  get 'home/about'
  root'home#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def about
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%=link_to 'Home', root_path, class:'navbar-brand'%>
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      <%=link_to 'About', home_about_path, class:'nav-link'%>
     </li>
      <li class="nav-item active">
      <%=link_to 'user', users_path, class:'nav-link'%>
     </li>
      <li class="nav-item active">
      <%=link_to 'orders', orders_path, class:'nav-link'%>
     </li>
     <li class="nav-item active">
      <%=link_to 'Products', products_path, class:'nav-link'%>
     </li>
     <li class="nav-item active">
      <%=link_to 'Address', addresses_path, class:'nav-link'%>
     </li>
  </ul>
    
  </div>
</nav>

app/views/home/about.html.erb
<center><h1>About me</h1></center> 
<br/>
<center><h5>Hello!🙂 This is Shashank, I am a tech enthusiast trying to learn new technologies and developing innovative projects👩‍💻💻
</h5></center>
<center><%= image_tag("tech.jpg")%></center>

app/views/home/index.html.erb
<center><br/><h1>Welcome to the home page!</h1></center>
<br/>

<center><h5>A Simple CRUD application to create, read, update and delete data...Developed using Ruby on Rails💎</h6></center>
<center><%= image_tag("crud.jpg")%></center>